# Generated by Django 4.0.6 on 2023-03-28 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medician',
            fields=[
                ('medician_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dob', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PHC',
            fields=[
                ('phc_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('mobile', models.IntegerField()),
                ('no_of_beds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='immunisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('vaccine_name', models.CharField(max_length=50)),
                ('no_of_vaccines', models.IntegerField()),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PHC.phc')),
            ],
        ),
        migrations.CreateModel(
            name='designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('medician_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PHC.medician')),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PHC.phc')),
            ],
        ),
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.IntegerField()),
                ('patient_name', models.CharField(max_length=50)),
                ('guardian_name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
                ('cause', models.CharField(max_length=50)),
                ('admission_time', models.DateTimeField(auto_now_add=True)),
                ('discharge_time', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('report', models.FileField(upload_to='pdf')),
                ('phc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PHC.phc')),
            ],
        ),
    ]
