# Generated by Django 4.0.6 on 2023-03-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phc',
            name='gmap_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phc',
            name='phc_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phc',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
