# Generated by Django 4.0.6 on 2023-03-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHC', '0002_phc_gmap_link_phc_phc_name_phc_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='status',
            new_name='discharge_status',
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharge_time',
            field=models.DateTimeField(null=True),
        ),
    ]
