# Generated by Django 4.1.7 on 2023-03-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHC', '0003_rename_status_admission_discharge_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phc',
            name='gmap_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
