# Generated by Django 4.1.7 on 2023-03-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHC', '0004_alter_phc_gmap_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phc',
            name='gmap_link',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='phc',
            name='summary',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
