# Generated by Django 4.1.7 on 2023-03-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PHC', '0005_alter_phc_gmap_link_alter_phc_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='blood_group',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='street',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='phc',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='guardian_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='patient_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='report',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
